---
# Tasks for installing Filebeat to webservers
  - name: Download FileBeat deb
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
      dest: /tmp/filebeat-7.6.1-amd64.deb

  - name: Install FileBeat deb
    apt:
      deb: /tmp/filebeat-7.6.1-amd64.deb

  - name: Drop in FileBeat config
    copy:
      src: filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes

