---
  - hosts: elk
    remote_user: azadmin
    become: True
    roles:
      - install-elk

  - hosts: webservers
    remote_user: azadmin
    become: True
    roles:
      - install-dvwa
      - install-filebeat
      - install-metricbeat
