---
# Tasks for installing Metricbeat to webservers
  - name: Download MetricBeat deb
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
      dest: /tmp/metricbeat-7.6.1-amd64.deb

  - name: Install MetricBeat deb
    apt: 
      deb: /tmp/metricbeat-7.6.1-amd64.deb

  - name: Drop in MetricBeat config
    copy:
      src: metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes

